// Package quiz defines the on-disk JSON model emitted by quizgen and consumed
// by the iOS app.
package quiz

import "time"

// SchemaVersion is the default schema version: mechanical-only bundles that v3
// iOS clients understand. The iOS client rejects payloads whose version it does
// not understand.
const SchemaVersion = 3

// SchemaVersionV4 is emitted when a bundle carries LLM-generated content
// (summaries and "llm" quizzes) plus the per-proposal source metadata. v4 adds
// only optional fields, so a v4 bundle is a strict superset of v3; it is served
// on a separate path until the iOS client accepts version 4 (see M3).
const SchemaVersionV4 = 4

// Bundle is the top-level structure written to quizzes.json.
//
// The single-valued Source* fields describe the primary upstream (kept for
// backward compatibility with v3 clients). When the bundle draws from more than
// one upstream, Sources lists every contributing source; it is omitted for
// single-source bundles, so their output is byte-identical to before and v3
// clients (which ignore unknown keys) are unaffected.
type Bundle struct {
	Version          int        `json:"version"`
	GeneratedAt      time.Time  `json:"generated_at"`
	SourceRepo       string     `json:"source_repo"`
	SourceFork       string     `json:"source_fork"`
	SourceCommit     string     `json:"source_commit,omitempty"`
	SourceLicense    string     `json:"source_license"`
	SourceLicenseURL string     `json:"source_license_url"`
	Sources          []Source   `json:"sources,omitempty"`
	Proposals        []Proposal `json:"proposals"`
}

// Source describes one upstream that contributed proposals to a bundle, for
// attribution and reproducibility.
type Source struct {
	Kind       string `json:"kind"` // "design-docs" | "github-issues"
	Repo       string `json:"repo"`
	Commit     string `json:"commit,omitempty"`
	License    string `json:"license"`
	LicenseURL string `json:"license_url"`
}

// Proposal groups the quizzes generated from one upstream item (a design/*.md
// file or a golang/go issue).
//
// The v4 fields (Summary, Status, SourceKind, IssueNumber) are omitted in v3
// bundles, so v3 output is byte-identical and v3 clients ignore them.
type Proposal struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	URL         string `json:"url"`
	Summary     string `json:"summary,omitempty"`      // v4: LLM-generated one-paragraph summary
	Status      string `json:"status,omitempty"`       // v4: "accepted" | "active" (issues)
	SourceKind  string `json:"source_kind,omitempty"`  // v4: "design-docs" | "github-issues"
	IssueNumber int    `json:"issue_number,omitempty"` // v4: golang/go issue number
	Quizzes     []Quiz `json:"quizzes"`
}

// Kind discriminates how a quiz was derived: from prose inline code, from a code
// block, or generated by an LLM (v4).
type Kind string

const (
	KindProse Kind = "prose"
	KindCode  Kind = "code"
	KindLLM   Kind = "llm"
)

// BlockType labels one rendered fragment of a quiz. The schema ships pre-parsed
// blocks so the iOS client renders a quiz by iterating the slice without
// re-parsing Markdown.
type BlockType string

const (
	// BlockText is literal prose text.
	BlockText BlockType = "text"
	// BlockInlineCode is an inline `code` span (rendered monospaced).
	BlockInlineCode BlockType = "inline_code"
	// BlockCodeBlock is a fragment of a fenced code block.
	BlockCodeBlock BlockType = "code_block"
	// BlockMask is a blank to fill in. Carries BlankIndex (no Value).
	BlockMask BlockType = "mask"
)

// Block is one fragment of a quiz's rendered body.
//
// Invariants (enforced by the generator and validated in tests):
//   - Type == BlockMask  => Value empty, BlankIndex set (∈ [0, len(Blanks))).
//   - Type != BlockMask  => Value non-empty, BlankIndex nil.
type Block struct {
	Type       BlockType `json:"type"`
	Value      string    `json:"value,omitempty"`
	BlankIndex *int      `json:"blank_index,omitempty"`
}

// Blank is one fill-in target: the answer plus its multiple-choice options.
// A single Blank may be referenced by several mask blocks (every occurrence of
// the same token in the unit), so answering once fills them all.
type Blank struct {
	Answer  string   `json:"answer"`
	Choices []string `json:"choices"`
}

// Quiz is one fill-in-the-blank question built from a single unit (a prose
// paragraph, a code block, or an LLM-generated stem). Blocks reconstructs the
// displayed body; each BlockMask points into Blanks. There is at least one Blank.
//
// The v4 fields (GenMethod, Difficulty) are omitted in v3 bundles.
type Quiz struct {
	ID         string  `json:"id"`
	Kind       Kind    `json:"kind"`
	Index      int     `json:"index"`
	GenMethod  string  `json:"gen_method,omitempty"` // v4: "mechanical" | "llm"
	Difficulty string  `json:"difficulty,omitempty"` // v4: optional difficulty label
	Blocks     []Block `json:"blocks"`
	Blanks     []Blank `json:"blanks"`
}

// MaskCount returns the number of BlockMask entries (mask occurrences, which
// may exceed the number of blanks).
func (q Quiz) MaskCount() int {
	n := 0
	for _, b := range q.Blocks {
		if b.Type == BlockMask {
			n++
		}
	}
	return n
}
